spring:
  profile: default, local
  datasource:
    url: jdbc:h2:file:~/data/distanceUnitDb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-cosole
      settings:
        trace: false
        web-allow-others: false

#---
#spring:
#  profile: postgresql
#  datasource:
#    initializantion-mode: always
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/distanceDB
#    driverClassName: org.postgresql.Driver
#    username: speedDbUser
#    password: Test1234
#  jpa:
#    database: POSTGRESQL
#    hibernate:
#      ddl-auto: update

server:
  port: 8001

management:
  endpoint:
    health:
      show-details: always